Repository amzn/MXFusion, pull requests merged in 2018-10, with the labels that each got.

#37 Add Gamma Distribution
  conftest.py
  mxfusion/components/distributions/__init__.py
  mxfusion/components/distributions/gamma.py
  testing/distributions/gamma_test.py
Labels: enhancement

#62 Add multiply kernel
  mxfusion/components/distributions/gp/kernels/kernel.py
  mxfusion/components/distributions/gp/kernels/multiply_kernel.py
  testing/distributions/gp/kernel_test.py
Labels: enhancement

#77 Fix divide by zero error if max_iter < n_prints
  mxfusion/inference/batch_loop.py
Labels: bug

#68 Validate shape of array variables
  mxfusion/components/variables/variable.py
  testing/core/variable_test.py
Labels: bug

#53 Added Bernoulli distribution + tests
  mxfusion/components/distributions/__init__.py
  mxfusion/components/distributions/bernoulli.py
  mxfusion/components/distributions/random_gen.py
  mxfusion/util/testutils.py
  testing/distributions/bernoulli_test.py
Labels: enhancement

#89 Expectation inference
  mxfusion/inference/__init__.py
  mxfusion/inference/expectation.py
  mxfusion/util/inference.py
  testing/inference/expectation_test.py
Labels: enhancement

#57 Add logistic variable transformation
  mxfusion/components/variables/__init__.py
  mxfusion/components/variables/var_trans.py
  testing/components/variables/var_trans_test.py
Labels: enhancement

#71 Dirichlet distribution
  mxfusion/components/distributions/__init__.py
  mxfusion/components/distributions/bernoulli.py
  mxfusion/components/distributions/categorical.py
  mxfusion/components/distributions/dirichlet.py
  mxfusion/components/distributions/gamma.py
  mxfusion/components/distributions/normal.py
  mxfusion/components/distributions/random_gen.py
  mxfusion/components/distributions/univariate.py
  mxfusion/components/distributions/wishart.py
  mxfusion/components/functions/function_evaluation.py
  mxfusion/components/variables/__init__.py
  mxfusion/components/variables/runtime_variable.py
  mxfusion/util/testutils.py
  testing/components/distributions/beta_test.py
  testing/components/distributions/categorical_test.py
  testing/components/distributions/dirichlet_test.py
  testing/components/distributions/gamma_test.py
  testing/components/distributions/gp/cond_gp_test.py
  testing/components/distributions/gp/gp_test.py
  testing/components/distributions/gp/kernel_test.py
  testing/components/distributions/normal_test.py
  testing/components/distributions/wishart_test.py
  testing/components/functions/function_evaluation_test.py
  testing/components/functions/mxfusion_function_test.py
  testing/components/functions/mxfusion_gluon_function_test.py
  testing/distributions/bernoulli_test.py
  testing/distributions/normal_mean_precision_test.py
  testing/models/factor_graph_test.py
Labels: enhancement

#95 Update the Inference documentation
  CONTRIBUTING.md
  docs/design/CIPs/CIPs.md
  docs/design/inference.md
  docs/design_documents/inference.md
  docs/design_documents/model_definition.md
  docs/design_documents/overview.md
  docs/design_proposals/design_proposal_guidelines.md
  mxfusion/inference/inference.py
Labels: Documentation
